#!/bin/sh

[ -z "${DROIDIAN_VCS_URL}" ] || DROIDIAN_EXTRA_ARGS="-DX-Droidian-VCS-URL=${DROIDIAN_VCS_URL}"
[ -z "${DROIDIAN_VCS_REV}" ] || DROIDIAN_EXTRA_ARGS="${DROIDIAN_EXTRA_ARGS} -DX-Droidian-VCS-Revision=${DROIDIAN_VCS_REV}"

exec /usr/bin/dpkg-gencontrol $@ ${DROIDIAN_EXTRA_ARGS}
